import { __ } from '@wordpress/i18n';

export default [
	__( 'Albania' ),
	__( 'Andorra' ),
	__( 'Armenia' ),
	__( 'Austria' ),
	__( 'Azerbaijan' ),
	__( 'Belarus' ),
	__( 'Belgium' ),
	__( 'Bosnia and Herzegovina' ),
	__( 'Bulgaria' ),
	__( 'Croatia' ),
	__( 'Cyprus' ),
	__( 'Czech Republic' ),
	__( 'Denmark' ),
	__( 'Estonia' ),
	__( 'Finland' ),
	__( 'France' ),
	__( 'Georgia' ),
	__( 'Germany' ),
	__( 'Greece' ),
	__( 'Hungary' ),
	__( 'Iceland' ),
	__( 'Ireland' ),
	__( 'Italy' ),
	__( 'Kazakhstan' ),
	__( 'Kosovo' ),
	__( 'Latvia' ),
	__( 'Liechtenstein' ),
	__( 'Lithuania' ),
	__( 'Luxembourg' ),
	__( 'Malta' ),
	__( 'Moldova' ),
	__( 'Monaco' ),
	__( 'Montenegro' ),
	__( 'Netherlands' ),
	__( 'North Macedonia' ),
	__( 'Norway' ),
	__( 'Poland' ),
	__( 'Portugal' ),
	__( 'Romania' ),
	__( 'Russia' ),
	__( 'San Marino' ),
	__( 'Serbia' ),
	__( 'Slovakia' ),
	__( 'Slovenia' ),
	__( 'Spain' ),
	__( 'Sweden' ),
	__( 'Switzerland' ),
	__( 'Turkey' ),
	__( 'Ukraine' ),
];
